name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/workflows/.github/workflows/swift_test_plugin.yml@main
    with:
      scheme: KipplePlugins-Package
      subcommand: build
    secrets:
      DISCORD_CI_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}
